### ISSUE TITLE
Placing head -> Chat Issue

### ISSUE THREAD

**Issue by alphabeticalDCB** [Zazsona/DecorHeads#12]
I'm having a huge issue when players place heads. When doing so, the chat is filled with a big chunk of text in chat for everyone to see. Could there be any possible remedy for this?
![Screenshot_2](https://user-images.githubusercontent.com/99226508/153112405-fe41cfa5-e13b-441f-86fb-3bfb63ceeee6.png)
![Screenshot_3](https://user-images.githubusercontent.com/99226508/153112416-8f517cea-d3de-4d3e-b40a-b0405b35b085.png)

Along side these screenshots, I will also provide a list of each plugin installed:
![Screenshot_4](https://user-images.githubusercontent.com/99226508/153112484-be77b14c-1f6b-4d60-9e00-d7f4a24c91bd.png)

As well as the chunk of text that appears in console after placing a head:

09.02 02:48:14 [Server] INFO Item: ItemStack{PLAYER_HEAD x 1, SKULL_META:{meta-type=SKULL, display-name={"extra":[{"text":"Beer"}],"text":""}, lore=[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"DecorHeads"}],"text":""}], internal=H4sIAAAAAAAA/02PS06DUBhGfw0miC7EiQkPi+nMWk17SfmxlPdISm/lcW9tKDS9LMGdODAapy7DFRg3IkOH55xv8ikACpwvqpaxh/p5XTAqg4QppyDdUloroPR6S+umoLtTkBt6aNqa7hQAOJLhJEhZS+GdCktNolxdRRbLBDF79hYqc0i5vSabQCzHxCS879ORORPDf9tBk4YDFhtWnmzm7ZIH6sxwGZ26Wsb9Pd6NNFv3BZZPOupWgV6m2V3OHC+7crz7DnW3iDnpXWbgxD84k6CKvYQnYazZIRY2D6qknAvkpMOO6Di2hutIBTiDY7LqP0gvlz9fr58OfPx+P77diAuAP4hnvAYSAQAA, PublicBukkitValues={decorheads:headkey=beer}, skull-owner=Beer}}
![Screenshot_9](https://user-images.githubusercontent.com/99226508/153112660-24d1bc7d-cc5f-4d0e-9102-078ef4181a29.png)

Thank you!

**Comment by Zazsona** [comment]
Cheers for the detailed report!
Had a bit of a poke about but I couldn't find the source for this in DecorHeads itself - Definitely looks like some sort of custom output though, so I don't think it's coming from any calls to base Minecraft or Bukkit/Spigot!

I suspect it might be a debugging line accidentally left over in one of the other plugins that's picking up on the fact DecorHeads blocks have custom metadata. If you get the chance, would you be able to set up a testing server, removing plugins a few at a time, and testing it out until the message no longer displays? Cheers!

I've tested DecorHeads against bPermissions, DeadChest, Essentials, Vault, WorldEdit, and WorldGuard, so those are likely A-OK!

**Comment by alphabeticalDCB** [comment]
I'll go ahead and mess around with the plugin removal and such and try to figure out which is the cause of it, thank you so much for helping looking into it!

**Comment by Zazsona** [comment]
Blimey, cheers for the speedy response! You beat me to the tag, haha!
Happy to help, and cheers for testing! Would love to hear the results! Feel free to pop back if you can't track anything down too, I'll have another look to see if it's on DH's side.
