### ISSUE TITLE
Adding New Heads Breaks Plugin For Me

### ISSUE THREAD

**Issue by DoomedIdeas** [Zazsona/DecorHeads#14]
Hello! A friend of mine is hosting a 1.19 server and using your plugin, where it works perfectly fine. However, when they used a heads.yml file ([headstxt.txt](https://github.com/Zazsona/DecorHeads/files/9078500/headstxt.txt) since github won't let me attach a .yml) that I customized, the plugin breaks and none of the heads appear in the world, even the non-modified heads. I checked the wiki and my file to see if there were any plugin-breaking mistakes, and I don't think that there are any. Did I miss something, and what can I do to make these custom heads work?

**Comment by Zazsona** [comment]
'Ello! Cheers for submitting a report & sharing the heads file! Great to see someone adding so many custom heads!
Having a quick poke around the head definitions look perfectly in line with the Wiki as you say! I suspect the issue might be on Line 2468 - `name: "Dog" Plushie`

Double quotes have special meaning in YAML (.yml) files, so I think that might be confusing the plugin! Try replacing that line with `name: "\"Dog\" Plushie"` - That should hopefully load and show in-game as `"Dog" Plushie`! Feel free to pop back if that doesn't do the trick!

**Comment by DoomedIdeas** [comment]
Thank you, that was the exact issue, and it works great now! I'll make sure to remember that when I add more custom heads in the future.

**Comment by Zazsona** [comment]
Whoop whoop! Fantastic! Feel free to swing by again if anything else goes arse up!
