### ISSUE TITLE
V2.3.0 and 2.3.1 spam Console

### ISSUE THREAD

**Issue by Loquos** [Zazsona/DecorHeads#15]
I just noticed that when any user is online, the Console gets spammed with this stuff:

![Screen Shot 2022-09-12 at 10 07 22](https://user-images.githubusercontent.com/30909616/189662765-2eb80238-7cc4-4c3d-b319-f15d1bc8cbbf.png)

Occasionally, there's a mention of DecorHeads `Could not pass event BlockFromToEvent to DecorHeads v2.3.0` so I tried disabling the plugin and the spam stops. This was a lovely plugin, and I'm no coder so I don't know if there's some conflict somewhere with another plugin I added or if there's some setting I need to fix, but it renders Console unusable so I'm keeping it disabled for now.

This spam showed up recently, after I updated from the 2.2.0 to 2.3.0 release. The only other plugin I added around the time the spam started was a legacy NickNames plugin (which shouldn't have any conflicts) and updated my HuskHomes version to 3.0.1.

Of note: When I first noticed the spam, it wasn't so much spam as the occasional line and sometimes the `Could not pass event BlockFromToEvent to DecorHeads v2.3.0` - I thought maybe this was because we were playing in 1.19.2 but I hadn't updated DecorHeads to 2.3.1. But last night, when I was checking something for a player, Console was flooded with these lines and I couldn't do anything in Console before it disappeared in the history. I just tried updating from 2.3.0 to 2.3.1 and the problem persists.

**Comment by Zazsona** [comment]
Cheers for the report! DecorHeads uses that event to make sure that when a head is destroyed by water it drops correctly, but seems something's going slightly wrong here!

Would you be able to provide a copy of the full error from your logs? There should be some lines that mention `com.zazsona.decorheads` before the `net.minecraft.server` ones that'll help track down why it's misbehaving!

Cheers!

**Comment by Loquos** [comment]
Sure! Here's the one from last night, when I noticed how bad it was. If you scroll down to [17:15:07] you can see when a user joins and things start going crazy.
[2022-09-11-2.log.gz](https://github.com/Zazsona/DecorHeads/files/9550448/2022-09-11-2.log.gz)

**Comment by Loquos** [comment]
Ooops. Forgot to add: the first mention of com.zazsona.decorheads is at [17:15:35]

**Comment by Zazsona** [comment]
Cheers! Looking at those logs, the DecorHeads block meta file may have become corrupted and the plugin doesn't know how to deal with it, can sometimes happen if the server crashes! You should find it in `/plugins/DecorHeads/blockMetadata.json`, shoot it over and I'll see if there's anything I can do to recover it! (if I'm right in my guess, haha!)

**Comment by Loquos** [comment]
Thanks! If that does turn out to be the issue, would a complete deletion and new install fix the problem?

Since Github won't allow .json files, I'm linking the file here: https://drive.google.com/file/d/1_BK-3VDC_fSompTsAwmWAFn2taJHMkZQ/view?usp=sharing

**Comment by Zazsona** [comment]
Yup, deleting that file should fix the errors! Sadly it's a bit too far gone to repair, but not to worry!

After deleting it, there's also a setting in the config called "head-meta-patcher", if you set that to true DecorHeads will try and restore the lost data to heads when they're broken! Just be weary it might conflict with any other heads plugins if you've got any installed!

Let me know how it goes!

**Comment by Loquos** [comment]
No other heads plugins used. And that seems to have done the trick. No more console spam. Thanks!
