### ISSUE TITLE
Missing skins

### ISSUE THREAD

**Issue by Frozy22** [Zazsona/DecorHeads#16]
![image](https://user-images.githubusercontent.com/47426301/195431908-69edd477-f9b9-424e-b996-a4b41ecc1c1d.png)
when starting the server, the heads lost their skins
there are no errors or warnings in the server console

paper - 1.19.2-135
decorheads - 2.3.1

**Comment by Zazsona** [comment]
Thanks for the report!
Looks like Mojang's servers are unable to find some of the skins. I'm hoping it's just a temporary issue, but I'll keep an eye on it!

Cheers!

**Comment by Frozy22** [comment]
You were right, the problem was from Mojang, today the skins are back.
Thanks for the answer.
