### ISSUE TITLE
Cannot read field "value" because "anotherString" is null

### ISSUE THREAD

**Issue by DoomedIdeas** [Zazsona/DecorHeads#17]
Hi! So sorry to bother you again, but I'm running a new server and I wanted to install DecorHeads. However, when I try to restart the server with DecorHeads installed, these issues pop up and none of the heads are recognized. Can you help me figure out what is wrong, and how to fix it? I have tried redownloading and replacing the .jar file, but it hasn't worked. The server is on 1.19.1, and I can supply any other information if you need it. Thank you so much!
`02.04 21:33:26 [Server] WARN Cannot read field "value" because "anotherString" is null
02.04 21:33:26 [Server] WARN java.lang.NullPointerException: Cannot read field "value" because "anotherString" is null
02.04 21:33:26 [Server] WARN at java.base/java.lang.String.compareTo(String.java:2012)
02.04 21:33:26 [Server] WARN at DecorHeads.jar//com.zazsona.decorheads.config.HeadUpdater.getUpdates(HeadUpdater.java:89)
02.04 21:33:26 [Server] WARN at DecorHeads.jar//com.zazsona.decorheads.config.HeadUpdater.updateHeadsFile(HeadUpdater.java:44)
02.04 21:33:26 [Server] WARN at DecorHeads.jar//com.zazsona.decorheads.Core.onEnable(Core.java:35)
02.04 21:33:26 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
02.04 21:33:26 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
02.04 21:33:26 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
02.04 21:33:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
02.04 21:33:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
02.04 21:33:26 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
02.04 21:33:26 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
02.04 21:33:26 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
02.04 21:33:26 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1124)
02.04 21:33:26 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
02.04 21:33:26 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Zazsona** [comment]
Haha, no worries mate!
Sounds like we've possibly got something strange in heads.yml again! Have a peek and make sure you've got a "version" property, like this one here! - https://github.com/Zazsona/DecorHeads/blob/master/src/main/resources/heads.yml#L5

If it's not there, you can copy the one from that file, setting the version to 2.3.0!

**Comment by DoomedIdeas** [comment]
Oh, I see what it is! The version was there, but the "heads:" underneath it wasn't. That seems to have fixed it, thank you so much!
