### ISSUE TITLE
Head Dupe

### ISSUE THREAD

**Issue by Philosoap** [Zazsona/DecorHeads#2]
Discovered a dupe when using DecorHeads along with Towny (and likely other land management plugins).

Player A is the mayor of the town, Venice. As mayor, they have access to place and break blocks in their town. Player A obtains a head and places it in their town.

Player B is the mayor of another town. They do not have access to place or break blocks in Venice. When Player B attempts to break the head that Player A placed earlier, the head stays there and does not break. However, a head drops like Player B really did break the head.

You can probably see where this is going. Player B can try to break the head over and over to drop unlimited amounts of heads.

**Comment by Zazsona** [comment]
Hmm, now that definitely doesn't sound quite right! Cheers for the heads up and recreation steps - I suspect you're probably right in that this'll manifest in other land management plugins too, I reckon it'll also extend to heads that drop from regular blocks, as the logic is largely identical, just harder to spot from non-guaranteed drop rates!

**Comment by Zazsona** [comment]
Sorry for the delay, this should be fixed as of: [Respect event cancellation](https://github.com/Zazsona/DecorHeads/commit/89b46b7352d35df72b56364d901d9cb591282db6)!
As expected, was also occurring under plugins such as WorldGuard, and effecting regular head drops too! Version 1.6.0 is live on [Spigot](https://www.spigotmc.org/resources/decorheads.88633/), and should be approved on [Bukkit ](https://dev.bukkit.org/projects/decorheads)in a couple of days!
