### ISSUE TITLE
No heads dropping on player death (2.0.0)

### ISSUE THREAD

**Issue by Roan-V** [Zazsona/DecorHeads#4]
Hey!

We've been using 2.0.0 on our server for a few days now, it works great, except 2 issues. (I'll put the second problem in another github issue)
This first one is that playerheads just don't drop when they get killed, even when explicitly setting the DecorHeads.DropHeads permission to true.
I also tested this with just decorheads and luckperms installed, so it shouldn't be a plugin incompatibility.

Currently running MC 1.17.1 on a paper fork (purpur-1285)

I don't really have more info to tell you I guess, feel free to let me know if you need something :)

**Comment by Zazsona** [comment]
Heyo! Glad to hear most of it's working well! Only two issues in a few days blows my guesstimates out the water, haha.
Thanks for your thorough testing again and isolating the plugin too, it's always a big help! Can't see any stupid mistakes in the code straight away, have you got your config handy so I can have a peek to see if I've got any checks going wonky? Cheers!

**Comment by Roan-V** [comment]
They're all completely default.

[heads.txt](https://github.com/Zazsona/DecorHeads/files/6843596/heads.txt)
[config.txt](https://github.com/Zazsona/DecorHeads/files/6843597/config.txt)
(.txt instead of .yml cause github doesn't like it otherwise)

**Comment by Zazsona** [comment]
Cheers! I've given it a go with Paper and the same Purpur build with LuckPerms and sadly not been able to recreate it, when setting the drop rate to 100% for both environmental deaths and player deaths they seem to drop consistently. (Though I did find another bug regarding stacking heads between reboots!)

Mind setting the drop rate to 100% and giving that a whirl? Might just be shockingly bad luck, haha.

**Comment by Roan-V** [comment]
:O
I did not notice that setting, that's my bad, sorry for waisting your time on that.
That would probably do it :P 
Will give it a whirl after our daily restart (unless there is a reload command that I missed?)

**Comment by Zazsona** [comment]
Ah-ha, no worries! It does get buried in the 1,000 line mess! 
No proper reload command yet sadly (The functionality's in the code, but I need to do some more testing before adding it as a command). Bukkit has `/reload` built in though which works for DecorHeads, but might cause other plugins to go a bit wonky!

Let me know how it goes when your restart runs!

**Comment by Roan-V** [comment]
Yup, that fixed it!
Who knew that setting your configs correctly would help ^_^

Thanks again.
