### ISSUE TITLE
/dhwiki command throwing warnings on non correct syntax (V2.0.0)

### ISSUE THREAD

**Issue by Roan-V** [Zazsona/DecorHeads#5]
Other Issue we've found is with the /dhwiki command. Not a critical issue per se, but console spam is never nice :P
Running the command without anything else specified throws an IndexOutOfBoundsException and tunning the command with a wrong/mistyped submenu throws an IllegalArgumentException
<details>
<summary>ArrayIndexOutOfBoundsException:</summary>

> [20:04:35 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
> [20:04:35 WARN]:        at com.zazsona.decorheads.command.WikiCommand.onCommand(WikiCommand.java:41)
> [20:04:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [20:04:35 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
> [20:04:35 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
> [20:04:35 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2309)
> [20:04:35 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2120)
> [20:04:35 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2101)
> [20:04:35 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
> [20:04:35 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
> [20:04:35 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
> [20:04:35 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [20:04:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
> [20:04:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
> [20:04:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
> [20:04:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
> [20:04:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [20:04:35 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
</details>

<details>
<summary>IllegalArgumentException:</summary>

> [20:03:54 WARN]: java.lang.IllegalArgumentException: Unknown submenu: test
> [20:03:54 WARN]:        at com.zazsona.decorheads.command.WikiCommand.onCommand(WikiCommand.java:49)
> [20:03:54 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [20:03:54 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
> [20:03:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
> [20:03:54 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2309)
> [20:03:54 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2120)
> [20:03:54 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2101)
> [20:03:54 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
> [20:03:54 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
> [20:03:54 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
> [20:03:54 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [20:03:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
> [20:03:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
> [20:03:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
> [20:03:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
> [20:03:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [20:03:54 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
</details>

(Just luckperms and decorheads installed, running MC1.17.1 purpur-1285)
As before, let me know if you need any more information.

**Comment by Zazsona** [comment]
Ha, whoops. I left a stack trace print out from when I was debugging it, nice catch! I've removed it for the next update.
