### ISSUE TITLE
Player head stacks are inconsistent between player joins.

### ISSUE THREAD

**Issue by Zazsona** [Zazsona/DecorHeads#6]
Cause is likely due to generating player heads from an OfflinePlayer instance returning Base64 texture data with timestamp and profile data pertaining to the offline profile, which is reloaded every reboot/player reconnect:
```
{
  "timestamp" : X,
  "profileId" : "Y",
  "profileName" : "Z",
  "signatureRequired" : true,
  "textures" : {
    "SKIN" : {
      "url" : "foo"
    }
  }
}
```
For consistent stacking, only the texture field should be loaded, as with "decor" heads:
```
{
  "textures" : {
    "SKIN" : {
      "url" : "foo"
    }
  }
}
```

However, this disables the ability of the head to update with the player's skin. As such, there are two approaches:
1. Full stacking support, but player heads do not update
2. No stacking support, but player heads do update

**Comment by Roan-V** [comment]
Personally I would vote for 1.
imo, having heads update is less "important" than having them stack.

In addition to that I've personally seen people switch their skin multiple times a day just to get a few different decoration heads.
So the non-update thing might even be beneficial for some.

**Comment by Zazsona** [comment]
That's great input to have, cheers! I was just thinking some players might be doing that so leaning towards the first myself!
(It may also be because the first is a lot easier to implement, haha)

**Comment by Zazsona** [comment]
As of 2.1.0, heads will now stack consistently between reboots and retain the skin. Heads generated on 2.1.0 or later will also retain the original skin when broken, instead of reloading to the player's current skin.
