### ISSUE TITLE
Prevents Slimefun drops

### ISSUE THREAD

**Issue by UnknownVariables-here** [Zazsona/DecorHeads#9]
There's no errors to show what goes wrong with this but apparently as soon as this plugin is installed Slimefun4 cargo monitors, generators, etc can no longer be dropped when broken in survival

**Comment by Zazsona** [comment]
Cheers for the report!
You're definitely right, DecorHeads is the plugin at fault here! I submitted a version 2.1.1 update to Bukkit for review just last night which should fix this, so keep an eye out for that and let me know if that fixes it or if the issue persists! I'll make another comment here when it's available!

Thanks again!

**Comment by Zazsona** [comment]
Cheers for waiting! 2.1.1 has finally cleared the review queue. Let me know if it fixes the issue!

Bukkit: https://dev.bukkit.org/projects/decorheads/files/3431035
Spigot: https://www.spigotmc.org/resources/decorheads.88633/

**Comment by Zazsona** [comment]
Tested with Slimefun4. Issue is resolved as of 2.1.1.
